# Method to attach image to item
def attach_image_to_item(item, image_path)
  item.item_image.attach(io: File.open(image_path), filename: File.basename(image_path), content_type: 'image/jpeg')
end
# Create items
[
  {
    name: "Amalgam of Death",
    item_type: "Feet",
    item_class: "Plate",
    level_requirement: 100,
    gold_price: 57500,
    rarity: "Epic",
    health: 900 ,
    armor: 60 ,
    magic_resistance: 25 ,
    dreadmight: 200 ,
    willpower: 200 ,
    luck: 100 ,
    image_path: 'app/assets/images/epic_items/amalgamofdeath.jpg'
  },
  {
    name: "Ashcaller",
    item_type: "Waist",
    item_class: "Belt",
    level_requirement: 100,
    gold_price: 57500,
    rarity: "Epic",
    health: 900 ,
    armor: 30 ,
    magic_resistance: 30 ,
    agility: 200 ,
    strength: 200 ,
    luck: 100 ,
    image_path: 'app/assets/images/epic_items/ashcaller.jpg'
  },
  {
    name: "Band of Might",
    item_type: "Finger",
    item_class: "Ring",
    level_requirement: 100,
    gold_price: 57500,
    rarity: "Epic",
    health: 630 ,
    critical_strike_chance: 4.5 ,
    critical_strike_damage: 0.45 ,
    strength: 100 ,
    image_path: 'app/assets/images/epic_items/bandofmight.jpg'
  },
  {
    name: "Bastion of Hope",
    item_type: "Chest",
    item_class: "Plate",
    level_requirement: 100,
    gold_price: 57500,
    rarity: "Epic",
    health: 1800 ,
    armor: 80 ,
    magic_resistance: 35 ,
    intelligence: 200 ,
    strength: 200 ,
    willpower: 100 ,
    image_path: 'app/assets/images/epic_items/bastionofhope.jpg'
  },
  {
    name: "Blackfang",
    item_type: "One-handed Weapon",
    item_class: "Dagger",
    level_requirement: 100,
    gold_price: 57500,
    rarity: "Epic",
    min_attack: 127 ,
    max_attack: 161 ,
    agility: 100 ,
    strength: 100 ,
    luck: 300 ,
    image_path: 'app/assets/images/epic_items/blackfang.jpg'
  },
  {
    name: "Burning Hatred",
    item_type: "Head",
    item_class: "Plate",
    level_requirement: 100,
    gold_price: 57500,
    rarity: "Epic",
    health: 900 ,
    armor: 60  ,
    magic_resistance: 25 ,
    dreadmight: 200 ,
    strength: 200 ,
    willpower: 100 ,
    image_path: 'app/assets/images/epic_items/burninghatred.jpg'
  },
  {
    name: "Cerberus",
    item_type: "Two-handed Weapon",
    item_class: "Mace",
    level_requirement: 100,
    gold_price: 57500,
    rarity: "Epic",
    min_spellpower: 66 ,
    max_spellpower: 819 ,
    intelligence: 200 ,
    strength: 200 ,
    willpower: 100 ,
    image_path: 'app/assets/images/epic_items/cerberus.jpg'
  },
  {
    name: "Cloak of Forbidden Rites",
    item_type: "Chest",
    item_class: "Cloth",
    level_requirement: 100,
    gold_price: 57500,
    rarity: "Epic",
    health: 1440 ,
    armor: 35 ,
    magic_resistance: 80 ,
    intelligence: 300 ,
    willpower: 100 ,
    luck: 100 ,
    image_path: 'app/assets/images/epic_items/cloakofforbiddenrites.jpg'
  },
  {
    name: "Crown of Twisted Souls",
    item_type: "Head",
    item_class: "Cloth",
    level_requirement: 100,
    gold_price: 57500,
    rarity: "Epic",
    health: 540 ,
    armor: 25 ,
    magic_resistance: 60 ,
    intelligence: 300 ,
    willpower: 100 ,
    luck: 100 ,
    image_path: 'app/assets/images/epic_items/crownoftwistedsouls.jpg'
  },
  {
    name: "Dying Sun",
    item_type: "One-handed Weapon",
    item_class: "Sword",
    level_requirement: 100,
    gold_price: 57500,
    rarity: "Epic",
    min_spellpower: 205 ,
    max_spellpower: 342 ,
    intelligence: 300 ,
    agility: 100 ,
    luck: 100 ,
    image_path: 'app/assets/images/epic_items/dyingsun.jpg'
  },
  {
    name: "Emissary of Twilight",
    item_type: "Two-handed Weapon",
    item_class: "Staff",
    level_requirement: 100,
    gold_price: 57500,
    rarity: "Epic",
    min_spellpower: 119 ,
    max_spellpower: 747 ,
    intelligence: 300 ,
    agility: 100 ,
    luck: 100 ,
    image_path: 'app/assets/images/epic_items/emissaryoftwilight.jpg'
  },
  {
    name: "Favor of Dusk",
    item_type: "Chest",
    item_class: "Cloth",
    level_requirement: 100,
    gold_price: 57500,
    rarity: "Epic",
    health: 1440 ,
    armor: 35 ,
    magic_resistance: 80 ,
    intelligence: 100 ,
    willpower: 300 ,
    luck: 100 ,
    image_path: 'app/assets/images/epic_items/favorofdusk.jpg'
  },
  {
    name: "Frostwind",
    item_type: "Two-handed Weapon",
    item_class: "Bow",
    level_requirement: 100,
    gold_price: 57500,
    rarity: "Epic",
    min_attack: 331 ,
    max_attack: 495 ,
    strength: 200 ,
    agility: 200 ,
    luck: 100 ,
    image_path: 'app/assets/images/epic_items/frostwind.jpg'
  },
  {
    name: "Malevolent Leather Wraps",
    item_type: "Chest",
    item_class: "Leather",
    level_requirement: 100,
    gold_price: 57500,
    rarity: "Epic",
    health: 1620 ,
    armor: 60 ,
    magic_resistance: 60 ,
    agility: 200 ,
    strength: 200 ,
    luck: 100 ,
    image_path: 'app/assets/images/epic_items/malevolentleatherwraps.jpg'
  },
  {
    name: "The Black Gate",
    item_type: "Shield",
    item_class: "Great Shield",
    level_requirement: 100,
    gold_price: 57500,
    rarity: "Epic",
    health: 1350 ,
    armor: 135 ,
    magic_resistance: 70 ,
    strength: 200 ,
    dreadmight: 200 ,
    willpower: 100 ,
    image_path: 'app/assets/images/epic_items/theblackgate.jpg'
  },
  {
    name: "Thundercall",
    item_type: "Shield",
    item_class: "Small Shield",
    level_requirement: 100,
    gold_price: 57500,
    rarity: "Epic",
    health: 900 ,
    armor: 90 ,
    magic_resistance: 90 ,
    intelligence: 100 ,
    willpower: 300 ,
    strength: 100 ,
    image_path: 'app/assets/images/epic_items/thundercall.jpg'
  },
  {
    name: "Vision of the Damned",
    item_type: "Head",
    item_class: "Cloth",
    level_requirement: 100,
    gold_price: 57500,
    rarity: "Epic",
    health: 540 ,
    armor: 25 ,
    magic_resistance: 60 ,
    intelligence: 300 ,
    agility: 100 ,
    luck: 100 ,
    image_path: 'app/assets/images/epic_items/visionofthedamned.jpg'
  },
  {
    name: "Walkers of Time",
    item_type: "Feet",
    item_class: "Cloth",
    level_requirement: 100,
    gold_price: 57500,
    rarity: "Epic",
    health: 540 ,
    armor: 25 ,
    magic_resistance: 60 ,
    intelligence: 300 ,
    agility: 100 ,
    luck: 100 ,
    image_path: 'app/assets/images/epic_items/walkersoftime.jpg'
  },
  {
    name: "Wall of Pain",
    item_type: "Shield",
    item_class: "Great Shield",
    level_requirement: 100,
    gold_price: 57500,
    rarity: "Epic",
    health: 1350 ,
    armor: 135 ,
    magic_resistance: 70 ,
    dreadmight: 300 ,
    willpower: 100 ,
    strength: 100 ,
    image_path: 'app/assets/images/epic_items/wallofpain.jpg'
  },
  {
    name: "Whispering Sorrow",
    item_type: "Two-handed Weapon",
    item_class: "Bow",
    level_requirement: 100,
    gold_price: 57500,
    rarity: "Epic",
    min_spellpower: 331 ,
    max_spellpower: 495 ,
    intelligence: 200 ,
    agility: 200 ,
    luck: 100 ,
    image_path: 'app/assets/images/epic_items/whisperingsorrow.jpg'
  },
  {
    name: "Zealous Crusade",
    item_type: "Head",
    item_class: "Plate",
    level_requirement: 100,
    gold_price: 57500,
    rarity: "Epic",
    health: 900 ,
    armor: 60 ,
    magic_resistance: 25 ,
    intelligence: 225 ,
    strength: 200 ,
    luck: 75 ,
    image_path: 'app/assets/images/epic_items/zealouscrusade.jpg'
  },
].each do |item_params|
  item = Item.new(item_params.except(:image_path))
  attach_image_to_item(item, item_params[:image_path])
  item.save
end
